# Generated by Django 2.0.4 on 2021-03-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=200)),
                ('last_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.IntegerField()),
                ('exchange', models.CharField(max_length=20, null=True)),
                ('sector', models.CharField(max_length=20, null=True)),
                ('industry', models.CharField(max_length=250, null=True)),
                ('related_stock', models.CharField(max_length=10, null=True)),
                ('active', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'db_table': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Stocks_Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_text', models.CharField(max_length=250, null=True)),
                ('article_link', models.CharField(max_length=200, null=True)),
                ('article_date', models.DateField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(blank=True, null=True)),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Stocks')),
            ],
            options={
                'verbose_name_plural': 'Stocks_Articles',
                'db_table': 'Stocks_Articles',
            },
        ),
    ]
