# Generated by Django 2.0.4 on 2021-03-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('log_state', models.CharField(max_length=20, null=True)),
                ('log_message', models.CharField(max_length=500, null=True)),
                ('creation_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Logging',
                'db_table': 'Logging',
            },
        ),
        migrations.CreateModel(
            name='Processing_Control',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('initial_creation_datetime', models.DateTimeField(blank=True, null=True)),
                ('final_creation_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Processing_Control',
                'db_table': 'Processing_Control',
            },
        ),
        migrations.AlterField(
            model_name='stocks_articles',
            name='article_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_articles',
            name='article_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logging',
            name='id_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Processing_Control'),
        ),
    ]
