# Generated by Django 2.0.4 on 2021-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210324_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='businessSumary',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
