# Generated by Django 2.0.4 on 2021-04-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_stocks_businesssumary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='businessSumary',
            new_name='businessSummary',
        ),
    ]
