# Generated by Django 2.0.4 on 2021-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_premarketstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='premarketstocks',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
